# application.yml


spring:


#datasource:
  ##    url: jdbc:mysql://db.soic.indiana.edu:3306/p565f18_srajash
  ##    password: my+sql=p565f18_srajash
  ##    username: p565f18_srajash

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hoosierevents
    password: root
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy



  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: fundoo93@gmail.com
    password: thisiswhyimhot
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false


  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
    # urls: ldap://localhost:12345  clientId: 270558996933505
    #      clientSecret: ee6aea892482bfe1ad914bf1055d4d6a
    # base: dc=loginComponent,dc=com
    # username: uid=admin
    # password: secret

    # Embedded Spring LDAP


    embedded:
      base-dn: dc=loginComponent,dc=com
      credential:
        password: secret
        username: uid=admin
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false
  social:
    facebook:
      app-secret: ee6aea892482bfe1ad914bf1055d4d6a
      app-id: 270558996933505
security:

  basic:
    enabled: false
